### ISSUE TITLE
Result malformed. 

### ISSUE THREAD

**Issue by afidegnum** [apache/incubator-age-viewer#14] opened 2021-11-22 13:36 UTC
diagrams are not drawn following this error:
after this query: 
```
SELECT * from cypher('text_test', $$
          MATCH (V)-[R:connects]-(V2)
          RETURN V,R,V2
$$) as (V agtype, R agtype, V2 agtype);
```

_$ SELECT * from cypher('text_test', $$ MATCH (V)-[R:connects]-(V2) RETURN V,R,V2 $$) as (V agtype, R agtype, V2 agtype);
Converting circular structure to JSON
--> starting at object with constructor 'Object'
--- property 'properties' closes the circle_

```
info: ::ffff:172.17.0.1 - - [22/Nov/2021:13:44:17 +0000] "POST /api/v1/cypher HTTP/1.1" 500 47
 {"timestamp":"2021-11-22 13:44:17"}
info: ::ffff:172.17.0.1 - - [22/Nov/2021:14:06:22 +0000] "GET /api/v1/db HTTP/1.1" 200 134
 {"timestamp":"2021-11-22 14:06:22"}
info: ::ffff:172.17.0.1 - - [22/Nov/2021:14:06:22 +0000] "GET /api/v1/db/metaChart HTTP/1.1" 500 2
 {"timestamp":"2021-11-22 14:06:22"}
info: ::ffff:172.17.0.1 - - [22/Nov/2021:14:06:23 +0000] "GET /api/v1/db/meta HTTP/1.1" 304 -
 {"timestamp":"2021-11-22 14:06:23"}
error: syntax error at or near "MATCH"
    at Parser.parseErrorMessage (/app/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 93,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '1',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1129',
  routine: 'scanner_yyerror'
}
info: ::ffff:172.17.0.1 - - [22/Nov/2021:14:14:52 +0000] "POST /api/v1/cypher HTTP/1.1" 500 47
 {"timestamp":"2021-11-22 14:14:52"}
info: ::ffff:172.17.0.1 - - [22/Nov/2021:14:15:41 +0000] "POST /api/v1/cypher HTTP/1.1" 200 137
 {"timestamp":"2021-11-22 14:15:41"}
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'properties' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/app/backend/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/app/backend/node_modules/express/lib/response.js:260:14)
    at _callee$ (/app/backend/build/controllers/cypherController.js:59:33)
    at tryCatch (/app/backend/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/app/backend/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/app/backend/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/app/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/app/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
info: ::ffff:172.17.0.1 - - [22/Nov/2021:14:16:03 +0000] "POST /api/v1/cypher HTTP/1.1" 500 154
 {"timestamp":"2021-11-22 14:16:03"}
info: ::ffff:172.17.0.1 - - [22/Nov/2021:14:16:13 +0000] "GET /api/v1/db/meta HTTP/1.1" 200 217
 {"timestamp":"2021-11-22 14:16:13"}


```

**Comment by david-m-m** [comment] 2021-11-22 16:31
Funny, I ran into the same error today as well. 
What I found is that it works fine as soon as the relations have at least one property set. 

I.e. I get the graph displayed when creating the relations like this:
`MATCH (a:Person),(b:Book) WHERE a.name='Jack' AND b.name='Hitchhiker' CREATE (a)-[r:Owns {name: a.name+'->'+b.name} ]->(b)`

while the following results in the described error:
`MATCH (a:Person),(b:Book) WHERE a.name='Jack' AND b.name='Hitchhiker' CREATE (a)-[r:Owns]->(b)`

**Comment by david-m-m** [comment] 2021-11-22 16:34
Just noticed: This is most likely the same issue as #9

**Comment by afidegnum** [comment] 2021-11-22 17:16
so, each edge must be added a property?

**Comment by afidegnum** [comment] 2021-11-22 17:23
@david-m-m I have a looping issue, can you please have a [look at it](https://github.com/rhizome-ai/apache-age-python/issues/7)?

**Comment by david-m-m** [comment] 2021-11-22 19:13
> so, each edge must be added a property? Thanks for the insight, I would have to amend my code.

Looks like it. Though I'm not familiar with the code, found out more by trial-and-error. 

Hopefully the developers of this project can gain & give more insight into this issue.

**Comment by david-m-m** [comment] 2021-11-22 19:16
> @david-m-m I have a looping issue, can you please have a [look at it](https://github.com/rhizome-ai/apache-age-python/issues/7)?

First: I'm not a developer and am not (yet?) deep into the matter. 
But I had issues addressing objects by their ID (when fiddling around on the console). So it may not be possible or work different that what we think.

**Comment by emotionbug** [comment] 2021-11-24 07:49
Thanks for waiting response.
I can't reproduce this issue. Are you using Docker?

**Comment by afidegnum** [comment] 2021-11-24 08:23
yes, i'm using docker here,

**Comment by emotionbug** [comment] 2021-11-24 08:24
@afidegnum
I just updated it on latest tag. I'll close this issue :)

**Closed by emotionbug** 2021-11-24 08:24 UTC
Labels: bug
